### ISSUE TITLE
Gatsbify the feedback widget styles

### ISSUE THREAD

**Issue by jlengstorf** [jlengstorf/gatsby-feedback-widget#4]
The feedback widget looks pretty good, but it could definitely use some polish and potentially subtle interaction sparkly goodness. @greglobinski has some bandwidth, so he's going to look at this next week.

@marcysutton we can get the feedback widget into the site before the style tweaks are in place — don't let this block any integration work with the .org site.

**Comment by nicholascapo** [comment]
A few random observations:
- The styling of the emoji's looks really weird until I clicked one of the choices and realized the middle one is selected by default (that's why it was purple).

![FF_fine](https://user-images.githubusercontent.com/3730819/55639308-afec9200-578e-11e9-94e7-345e6767b5ef.png)

- "Poor" is the only emoji with color on Firefox 66 (it's yellow, while the others are black and white)

![FF_great](https://user-images.githubusercontent.com/3730819/55639326-b975fa00-578e-11e9-8161-71507d005a1d.png)

- The Emoji's aren't on the same row in Chromium 72

![CH_rows](https://user-images.githubusercontent.com/3730819/55639329-bbd85400-578e-11e9-82d5-6a7bab272b29.png)

- I'm unsure about the interactions of the "Was this doc..." button while I am using the Submit dialog, maybe the dialog should cover the button?

**Comment by greglobinski** [comment]
Thank you @nicholascapo, 

I believe all the issues you reported will be solved with new styling. The most important change is we will you `svg` icons instead of Emoji's so  the 'faces' will look the same everywhere.

**Comment by jlengstorf** [comment]
@nicholascapo oof those emojis... 😅 

Thanks so much for adding these!

**Comment by jlengstorf** [comment]
@greglobinski we just merged #5. When you have a chance, please merge those changes into your branch. Really looking forward to seeing the updated styles! Thanks again!

**Comment by jlengstorf** [comment]
Done in #7
